apiVersion: v1
kind: Service
metadata:
  name: elastic-python-service
spec:
  selector:
    app: elastic-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-python
spec:
  selector:
    matchLabels:
      app: elastic-python
  replicas: 4
  template:
    metadata:
      labels:
        app: elastic-python
    spec:
      containers:
      - name: elastic-python
        image: elastic-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
